name: Build APK

on:
  push:
    branches: [ main, master, rb ]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK
        run: ./gradlew assembleBaseRelease

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/base/release/*-arm*.apk

      - name: Upload APKs to Release (only on tag push)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/base/release/*-arm*.apk
          prerelease: true
